#!/usr/bin/env python3
"""Build infographic documentation for the original SeeLinks web UI."""

from __future__ import annotations

from html import escape
from pathlib import Path
import textwrap


SCRIPT_PATH = Path(__file__).resolve()
PACK_DIR = SCRIPT_PATH.parents[1]
NARRATIVE_DIR = PACK_DIR / "narrative"
NOTES_DIR = NARRATIVE_DIR / "notes"
ASSET_DIR = NARRATIVE_DIR / "assets" / "infographics"
NOTE_PATH = NOTES_DIR / "seelinks-web-ui-reference.md"

GENERATED_MARKER = (
    "<!-- Generated by research/hmrc-beyond-hype/tools/build_seelinks_ui_infographics.py. -->"
)

SOURCE_SUMMARY = (
    "Source: original SeeLinks web UI, branch datapacks, commit 7983b2e; "
    "observed from docs/ui-current.md, docs/ui-current-callouts.md, "
    "docs/user-guide.md, and apps/web/src/routes/+page.svelte."
)


class Svg:
    def __init__(self, width: int, height: int, title: str) -> None:
        self.width = width
        self.height = height
        self.parts: list[str] = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
            f"<title>{escape(title)}</title>",
            '<rect width="100%" height="100%" fill="#f7faf8"/>',
        ]

    def add(self, value: str) -> None:
        self.parts.append(value)

    def rect(
        self,
        x: int,
        y: int,
        w: int,
        h: int,
        fill: str = "#ffffff",
        stroke: str = "#b7c7c3",
        rx: int = 8,
        width: int = 2,
        dash: bool = False,
    ) -> None:
        dash_attr = ' stroke-dasharray="8 6"' if dash else ""
        self.add(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{width}"{dash_attr}/>'
        )

    def line(self, x1: int, y1: int, x2: int, y2: int, stroke: str = "#33645d", width: int = 2, dash: bool = False) -> None:
        dash_attr = ' stroke-dasharray="7 6"' if dash else ""
        self.add(
            f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{stroke}" stroke-width="{width}"{dash_attr}/>'
        )

    def arrow(self, x1: int, y1: int, x2: int, y2: int, stroke: str = "#33645d", width: int = 2) -> None:
        self.line(x1, y1, x2, y2, stroke, width)
        if x2 >= x1:
            points = f"{x2},{y2} {x2 - 10},{y2 - 6} {x2 - 10},{y2 + 6}"
        else:
            points = f"{x2},{y2} {x2 + 10},{y2 - 6} {x2 + 10},{y2 + 6}"
        self.add(f'<polygon points="{points}" fill="{stroke}"/>')

    def text(self, x: int, y: int, text: str, size: int = 16, fill: str = "#1c2f2b", weight: int | str = 400) -> None:
        self.add(
            f'<text x="{x}" y="{y}" font-family="Inter, Arial, sans-serif" '
            f'font-size="{size}" font-weight="{weight}" letter-spacing="0" fill="{fill}">{escape(text)}</text>'
        )

    def multiline(
        self,
        x: int,
        y: int,
        text: str,
        width_chars: int,
        size: int = 14,
        fill: str = "#24413c",
        line_height: int | None = None,
        weight: int | str = 400,
    ) -> int:
        line_height = line_height or size + 6
        lines = []
        for paragraph in text.split("\n"):
            if not paragraph.strip():
                lines.append("")
                continue
            lines.extend(textwrap.wrap(paragraph, width_chars, break_long_words=False) or [""])
        cursor = y
        for line in lines:
            self.text(x, cursor, line, size=size, fill=fill, weight=weight)
            cursor += line_height
        return cursor

    def pill(self, x: int, y: int, text: str, fill: str = "#e5f2ee", stroke: str = "#31756c", text_fill: str = "#123630") -> None:
        width = max(92, 12 * len(text) + 26)
        self.rect(x, y, width, 30, fill=fill, stroke=stroke, rx=15)
        self.text(x + 14, y + 20, text, size=13, fill=text_fill, weight=700)

    def callout(self, x: int, y: int, number: int, label: str, target_x: int, target_y: int) -> None:
        self.line(x, y, target_x, target_y, stroke="#1f5f56", width=2)
        self.add(f'<circle cx="{x}" cy="{y}" r="16" fill="#1f5f56"/>')
        self.text(x - (7 if number < 10 else 11), y + 5, str(number), size=14, fill="#ffffff", weight=800)
        self.text(x + 24, y + 5, label, size=13, fill="#123630", weight=700)

    def finish(self) -> str:
        self.parts.append("</svg>")
        return "\n".join(self.parts) + "\n"


def header(svg: Svg, title: str, subtitle: str) -> None:
    svg.rect(24, 20, svg.width - 48, 78, fill="#ffffff", stroke="#a9bdb8", rx=10)
    svg.text(48, 55, title, size=25, fill="#132f2a", weight=800)
    svg.text(48, 82, subtitle, size=14, fill="#3d5b55")


def footer(svg: Svg) -> None:
    svg.text(36, svg.height - 24, SOURCE_SUMMARY, size=12, fill="#526963")


def draw_overview() -> str:
    svg = Svg(1600, 980, "SeeLinks web UI anatomy")
    header(svg, "SeeLinks Web UI Anatomy", "Full-screen information browser: facet sidebar, view controls, tile grid, detail dock, and output tools.")

    svg.rect(38, 122, 420, 800, fill="#eef5f2", stroke="#8eb0a9", rx=14)
    svg.text(64, 156, "Left sidebar", size=21, weight=800)
    panels = [
        ("Order by", "Multi-facet sort stack; chip precedence, direction, legend include/exclude.", 178, 100),
        ("Facets", "Open, pin, drag-reorder, auto-order values, click/right-click/double-click chips.", 296, 176),
        ("Links", "Facet-driven related-value summary for quick highlighting.", 490, 82),
        ("MCP packs", "Lists external MCP resources when configured; load switches pack.", 590, 86),
        ("Collections, print, AI export", "Save selected items, reopen sets, print selection, copy or download AI JSON.", 694, 122),
        ("Tile text and editing", "Choose tile title/subtitle fields and apply new facet values when editing is enabled.", 836, 70),
    ]
    for title, body, y, h in panels:
        svg.rect(62, y, 372, h, fill="#ffffff", stroke="#bdd1cc")
        svg.text(84, y + 28, title, size=16, weight=800)
        svg.multiline(84, y + 54, body, 46, size=13, fill="#31504a")

    svg.rect(492, 122, 1068, 800, fill="#ffffff", stroke="#8eb0a9", rx=14)
    svg.text(522, 156, "Main workspace", size=21, weight=800)
    svg.rect(522, 178, 1008, 146, fill="#eef4fb", stroke="#9ab5cf")
    svg.text(548, 210, "View header and mode controls", size=17, weight=800)
    svg.multiline(
        548,
        238,
        "Title/count, mode description, Grid/Outline/Graph/Timeline/Reading tabs, dataset picker, JSON/JSONL/OpenAPI import, About intro launcher.",
        95,
        size=13,
    )
    svg.rect(548, 274, 440, 32, fill="#ffffff", stroke="#aac0d5", rx=16)
    svg.text(568, 296, "Search name...  | Clear | status", size=13, fill="#405a66")
    svg.rect(1006, 274, 500, 32, fill="#ffffff", stroke="#aac0d5", rx=16)
    svg.text(1026, 296, "Choose highlighted | Choose unhighlighted | Undo | Reset", size=13, fill="#405a66")

    svg.rect(522, 344, 1008, 64, fill="#f3f6f5", stroke="#c2d1cf")
    svg.text(548, 372, "Selection summary, collection profile, print status, view-history chips, import and service-worker messages.", size=14)

    svg.rect(522, 430, 1008, 210, fill="#fff7e8", stroke="#cfae6c")
    svg.text(548, 462, "Docked detail panel", size=17, weight=800)
    svg.multiline(
        548,
        490,
        "Appears when an item is open. Includes a tile strip for stepping through the current view, optional rollup cards, detail title/subtitle, Previous/Next/Close, Overview and Images tabs, and pack-specific detail layouts.",
        95,
        size=13,
    )
    for i in range(9):
        x = 558 + i * 92
        svg.rect(x, 562, 72, 46, fill="#ffffff", stroke="#d7bb7d", rx=6)
        svg.text(x + 18, 592, f"tile {i + 1}", size=12, fill="#6d4b0d")

    svg.rect(522, 666, 1008, 226, fill="#f8fbfa", stroke="#bdd1cc")
    svg.text(548, 698, "Tile grid / records viewer", size=17, weight=800)
    svg.multiline(
        548,
        724,
        "Single click selects a tile. Double click opens it. Tiles show image/icon, title, subtitle, category path or order summary, selected/highlighted/open states, and optional colour-by-facet background.",
        92,
        size=13,
    )
    colors = ["#e4f2ee", "#fff1d1", "#e6eefb", "#fde7ef", "#eee8fb", "#e9f4dd"]
    for row in range(2):
        for col in range(7):
            x = 558 + col * 132
            y = 786 + row * 54
            svg.rect(x, y, 106, 38, fill=colors[(row * 7 + col) % len(colors)], stroke="#8fa9a4", rx=6)
            svg.text(x + 12, y + 24, f"Card {row * 7 + col + 1}", size=12)

    callouts = [
        (1, "Facet list", 456, 356, 270, 380),
        (2, "Output panels", 456, 728, 244, 742),
        (3, "Mode tabs", 1510, 202, 1190, 202),
        (4, "Search/actions", 1510, 292, 1280, 292),
        (5, "Detail dock", 1510, 494, 1188, 518),
        (6, "Tile grid", 1510, 780, 1248, 800),
    ]
    for number, label, x, y, tx, ty in callouts:
        svg.callout(x, y, number, label, tx, ty)

    footer(svg)
    return svg.finish()


def draw_interactions() -> str:
    svg = Svg(1600, 1100, "SeeLinks facet and tile interactions")
    header(svg, "Facet And Tile Interaction Model", "The original SeeLinks UI is built around highlighting, reducing, ordering, colouring, and collecting visible records.")

    columns = [
        ("Facet header", "Click opens or closes. Pin keeps it open. Drag header reorders facets. Drag facet name to the grid pins it and colours tiles.", 48, "#eef5f2"),
        ("Facet value chip", "Click sets primary highlight. Right-click Adjust adds/removes within the facet. Double-click chooses that value. Drag reorders values or creates grid rollup.", 424, "#eef4fb"),
        ("Tile grid", "Single click selects. Double click opens. Drop facet names for colour legends. Drop facet values for rollup cards.", 800, "#fff7e8"),
        ("Toolbar/history", "Choose highlighted reduces to matches. Choose unhighlighted keeps non-matches. Undo view and history chips restore prior reductions.", 1176, "#f7ecf1"),
    ]
    for title, body, x, fill in columns:
        svg.rect(x, 132, 340, 180, fill=fill, stroke="#9db9b2", rx=14)
        svg.text(x + 24, 168, title, size=19, weight=800)
        svg.multiline(x + 24, 202, body, 34, size=14)

    svg.text(56, 374, "Core gestures", size=20, weight=800)
    gestures = [
        ("Click chip", "highlight matching records; count shows highlighted/total when active", 74, 420, 330, 420),
        ("Right-click chip", "adjust additive highlights within the same facet", 74, 500, 330, 500),
        ("Double-click chip", "choose that value and reduce the current view", 74, 580, 330, 580),
        ("Drag chip", "reorder facet values or drop on grid to create a rollup card", 74, 660, 330, 660),
        ("Drag facet name", "drop on grid to pin facet and apply tile colour legend", 74, 740, 330, 740),
        ("Click tile", "toggle manual selection for collection, print, or manual reduce", 74, 820, 330, 820),
        ("Double-click tile", "open docked detail view with tile strip and tabs", 74, 900, 330, 900),
    ]
    for action, result, x, y, tx, ty in gestures:
        svg.rect(x, y - 24, 204, 42, fill="#ffffff", stroke="#9bb8b2", rx=21)
        svg.text(x + 18, y + 5, action, size=14, weight=800)
        svg.arrow(x + 210, y - 2, tx, ty - 2)
        svg.multiline(tx + 18, ty + 4, result, 42, size=13)

    svg.rect(760, 370, 780, 286, fill="#ffffff", stroke="#9bb8b2", rx=14)
    svg.text(790, 408, "Tile state vocabulary", size=20, weight=800)
    states = [
        ("Selected", "manual selection set; exported, printable, collectable"),
        ("Highlighted", "matches current facet highlight expression"),
        ("Active/Open", "current detail-card item"),
        ("Coloured", "tile background comes from active facet value order"),
        ("Rollup", "facet-value summary card dropped into the grid"),
        ("Missing image", "visible badge for missing Micropedia media"),
    ]
    for i, (label, body) in enumerate(states):
        x = 792 + (i % 2) * 360
        y = 446 + (i // 2) * 62
        svg.pill(x, y, label, fill=["#e4f2ee", "#fff1d1", "#e6eefb", "#fde7ef", "#eee8fb", "#e9f4dd"][i])
        svg.multiline(x + 140, y + 12, body, 25, size=12)

    svg.rect(760, 696, 780, 300, fill="#ffffff", stroke="#9bb8b2", rx=14)
    svg.text(790, 734, "Reduction workflow", size=20, weight=800)
    steps = [
        ("1. Highlight", "Use facet chip click/Adjust or link summary."),
        ("2. Choose", "Keep highlighted or keep unhighlighted."),
        ("3. Record", "Pushes a history entry with label, count, total, and highlight snapshot."),
        ("4. Continue", "Repeat inside the smaller current view."),
        ("5. Undo/reset", "Use history chip, Undo view, or Reset."),
    ]
    for i, (label, body) in enumerate(steps):
        x = 800 + i * 140
        y = 812
        svg.rect(x, y, 118, 72, fill="#eef5f2", stroke="#7da69e", rx=10)
        svg.text(x + 14, y + 26, label, size=13, weight=800)
        svg.multiline(x + 14, y + 48, body, 17, size=10)
        if i < len(steps) - 1:
            svg.arrow(x + 120, y + 36, x + 136, y + 36)

    footer(svg)
    return svg.finish()


def draw_views() -> str:
    svg = Svg(1600, 1040, "SeeLinks views and detail surfaces")
    header(svg, "Views, Detail Surfaces, And Output Tools", "Every visible surface has a role: browse, narrow, inspect, collect, print, export, or edit.")

    view_cards = [
        ("Grid", "Default records viewer. Tile image/icon plus title/subtitle; selection, highlight, active, colour, rollup states.", "#e4f2ee"),
        ("Outline", "Category hierarchy view for slash-delimited category paths.", "#e6eefb"),
        ("Graph", "Knowledge graph summary of item/facet/link structure.", "#fff1d1"),
        ("Timeline", "Dated entries view when date-like fields exist.", "#fde7ef"),
        ("Reading", "Reader mode for longer text-oriented packs.", "#eee8fb"),
    ]
    for i, (title, body, fill) in enumerate(view_cards):
        x = 54 + i * 302
        svg.rect(x, 142, 270, 150, fill=fill, stroke="#8baaa4", rx=14)
        svg.text(x + 22, 180, title, size=21, weight=800)
        svg.multiline(x + 22, 212, body, 30, size=13)

    svg.rect(54, 340, 698, 560, fill="#ffffff", stroke="#9bb8b2", rx=14)
    svg.text(88, 382, "Docked detail card", size=22, weight=800)
    detail_sections = [
        ("Tile strip", "Horizontal navigation through the current view; accepts facet/facet-value drops like the main grid."),
        ("Header", "Item title, category path, Previous, Next, Close."),
        ("Overview tab", "Pack-specific detail layouts: UK Public AI, World Pulse metrics, Wikipedia, Micropedia, Pond Watch, API calls, fallback summary."),
        ("Images tab", "Image gallery with captions; hero image double-click jumps here."),
        ("Related/resources", "Related rows, source links, Wikipedia/Wikidata/Data Commons/API links when present."),
    ]
    for i, (title, body) in enumerate(detail_sections):
        y = 420 + i * 86
        svg.rect(90, y, 616, 62, fill="#f7faf9", stroke="#c7d8d4", rx=8)
        svg.text(112, y + 26, title, size=15, weight=800)
        svg.multiline(260, y + 24, body, 52, size=12)

    svg.rect(804, 340, 742, 560, fill="#ffffff", stroke="#9bb8b2", rx=14)
    svg.text(838, 382, "Left-sidebar output and configuration panels", size=22, weight=800)
    tools = [
        ("MCP packs", "Show remote pack resources when VITE_MCP_BASE_URL is configured; Load replaces current pack."),
        ("Collections", "Save current manual selection to IndexedDB-backed named lists; reopen later."),
        ("Printing", "Print selected records with pack limit and print templates."),
        ("AI export", "Copy or download current view JSON with full records and selected/highlighted flags."),
        ("Tile text", "Choose title/subtitle fields, template title, small ID badge, reset preferences."),
        ("Editing", "Readonly, prompted, or full modes; apply property/value to selected items."),
    ]
    for i, (title, body) in enumerate(tools):
        y = 420 + i * 70
        svg.rect(840, y, 660, 50, fill="#f7faf9", stroke="#c7d8d4", rx=8)
        svg.text(862, y + 22, title, size=14, weight=800)
        svg.multiline(1018, y + 20, body, 48, size=11)

    svg.rect(54, 930, 1492, 54, fill="#eef5f2", stroke="#9bb8b2", rx=10)
    svg.text(
        86,
        964,
        "Design implication for HMRC pack: keep the grid as the primary surface, and make side panels dense, persistent, and interaction-first.",
        size=15,
        weight=800,
    )

    footer(svg)
    return svg.finish()


def draw_data_flow() -> str:
    svg = Svg(1600, 1040, "SeeLinks data and state flow")
    header(svg, "Data, State, And Export Flow", "Packs feed records and property definitions; UI state transforms the current view; outputs preserve selection/highlight context.")

    lanes = [
        ("Inputs", 76, "#eef4fb"),
        ("Normalization", 364, "#eef5f2"),
        ("Interactive state", 652, "#fff7e8"),
        ("Outputs", 1040, "#f7ecf1"),
    ]
    for title, x, fill in lanes:
        svg.rect(x, 140, 230, 790, fill=fill, stroke="#9bb8b2", rx=14)
        svg.text(x + 26, 178, title, size=21, weight=800)

    boxes = {
        "Static packs": (104, 228),
        "URL pack query": (104, 330),
        "JSON/JSONL import": (104, 432),
        "OpenAPI import": (104, 534),
        "MCP resources": (104, 636),
        "Intro markdown": (104, 738),
        "Pack/item schema": (392, 228),
        "Property definitions": (392, 330),
        "Facet counts": (392, 432),
        "Link summary": (392, 534),
        "Tile labels": (392, 636),
        "Pack-specific detail layout": (392, 738),
        "Query/filter/highlight": (680, 228),
        "Current items": (680, 330),
        "Selection set": (680, 432),
        "Sort/order stack": (680, 534),
        "Colour facet + rollups": (680, 636),
        "History stack": (680, 738),
        "Collections": (1068, 228),
        "Print worksheet": (1068, 330),
        "AI context JSON": (1068, 432),
        "Detail reader/gallery": (1068, 534),
        "Graph/timeline/reading": (1068, 636),
        "Local preferences": (1068, 738),
    }
    for label, (x, y) in boxes.items():
        svg.rect(x, y, 174, 54, fill="#ffffff", stroke="#91afa9", rx=9)
        svg.multiline(x + 14, y + 24, label, 20, size=13, weight=800)

    arrows = [
        ("Static packs", "Pack/item schema"),
        ("URL pack query", "Pack/item schema"),
        ("JSON/JSONL import", "Pack/item schema"),
        ("OpenAPI import", "Pack/item schema"),
        ("MCP resources", "Pack/item schema"),
        ("Intro markdown", "Pack-specific detail layout"),
        ("Pack/item schema", "Property definitions"),
        ("Property definitions", "Facet counts"),
        ("Facet counts", "Query/filter/highlight"),
        ("Link summary", "Query/filter/highlight"),
        ("Tile labels", "Current items"),
        ("Pack-specific detail layout", "Detail reader/gallery"),
        ("Query/filter/highlight", "Current items"),
        ("Current items", "AI context JSON"),
        ("Selection set", "Collections"),
        ("Selection set", "Print worksheet"),
        ("Sort/order stack", "Current items"),
        ("Colour facet + rollups", "Current items"),
        ("History stack", "Current items"),
        ("Current items", "Graph/timeline/reading"),
        ("Current items", "Detail reader/gallery"),
        ("Sort/order stack", "Local preferences"),
        ("Colour facet + rollups", "Local preferences"),
    ]
    for start, end in arrows:
        sx, sy = boxes[start]
        ex, ey = boxes[end]
        svg.arrow(sx + 174, sy + 27, ex, ey + 27, stroke="#2f6f65", width=2)

    svg.rect(76, 956, 1430, 48, fill="#ffffff", stroke="#9bb8b2", rx=10)
    svg.text(
        104,
        986,
        "Persistence: collections use IndexedDB; facet order, facet-value order, sort exclusions, sort stack, visibility, and tile text preferences use localStorage.",
        size=14,
        weight=800,
    )

    footer(svg)
    return svg.finish()


def build_note() -> str:
    return f"""{GENERATED_MARKER}
---
tags:
  - seelinks
  - datapack
  - design
  - navigation
  - workflow
publication_status: "published UI reference generated from original SeeLinks source snapshot"
---

# SeeLinks Web UI Reference

This note captures the original SeeLinks web interface as a visual specification for the HMRC narrative workbench UI pass.

Source snapshot: original SeeLinks branch `datapacks`, commit `7983b2e` (`Add geography ontology graph + rollup UI`). The source files read for this note were `docs/ui-current.md`, `docs/ui-current-callouts.md`, `docs/user-guide.md`, and `apps/web/src/routes/+page.svelte`. Local uncommitted SeeLinks changes in devcontainer files were not used.

## Infographics

- [Web UI anatomy](../assets/infographics/seelinks-web-ui-anatomy.svg)
- [Facet and tile interaction model](../assets/infographics/seelinks-facet-tile-interactions.svg)
- [Views, detail surfaces, and output tools](../assets/infographics/seelinks-views-detail-output.svg)
- [Data, state, and export flow](../assets/infographics/seelinks-data-state-flow.svg)

## Complete UI Inventory

### Global Layout

- Resizable left sidebar.
- Main workspace.
- View title and mode description.
- View-mode tabs: Grid, Outline, Graph, Timeline, Reading.
- Dataset picker.
- Load JSON/JSONL.
- Load API example.
- About/intro launcher when pack intro content exists.
- Sticky search and action bar.
- Optional intro page.
- Selection summary.
- Optional collection profile.
- Optional print/import/service-worker status messages.
- History bar.
- Grid, detail dock, and alternate view surfaces.

### Sidebar Panels

- Order by panel with multi-facet sort stack.
- Sort precedence chip and direction toggle.
- Per-sort legend for including or excluding values.
- Facets panel with metadata toggle.
- Facet open/close.
- Facet pin/unpin.
- Facet drag-reorder.
- Facet sort/order-by add/remove.
- Facet value auto-order and clear-order.
- Facet value drag-reorder.
- Links panel summarising related facet values.
- MCP Packs panel when `VITE_MCP_BASE_URL` is configured.
- Collections panel with collection name input, Save from selection, and Open.
- Printing panel with print limit and Print selection.
- AI export panel with Copy AI context and Download AI context.
- Tile Text panel for title field, subtitle field, title template, small ID badge, and reset.
- Editing panel for mode, property, value, and Apply to selected.

### Facet Interactions

- Click a facet header to open or close it.
- Pin a facet to keep it open.
- Drag a facet header to reorder facets.
- Drag a facet name onto the tile grid to pin that facet, open it, and colour tiles by that facet's value order.
- Click a facet value to set the primary highlight.
- Right-click a facet value to Adjust, adding or removing highlight values within that facet.
- Double-click a facet value to choose that highlighted value and reduce the current view.
- Drag facet values to reorder values.
- Drag a facet value onto the tile grid to create a rollup card and apply the related colour legend.
- Highlight counts switch from total counts to highlighted/total counts when highlighting is active.

### Tile And Grid Interactions

- Single-click a tile to toggle manual selection.
- Double-click a tile to open the docked detail card.
- Selected, highlighted, active/open, missing-image, and coloured-by-facet states are visually distinct.
- Tiles can show image/icon, small ID badge, title, subtitle, category path, order-by summary, tile colour reason, and state text.
- The grid accepts facet drops and facet-value drops.
- Rollup cards show value, count, fraction, progress bar, Expand/Collapse, Remove, and Clear all.

### View Reduction And History

- Choose highlighted reduces the current view to highlighted records.
- Choose unhighlighted reduces the current view to non-highlighted records.
- If no facet highlight is active, those commands operate on manual tile selection.
- Each reduction pushes a history entry containing label, count, total, polarity, facet/value metadata, and highlight snapshot.
- Undo view steps back through history.
- History chips reopen earlier reductions.
- Reset clears filters and returns to the full pack.

### Detail Surface

- Docked detail panel appears above the grid when an item is open.
- Tile strip supports quick stepping through the current set.
- Previous, Next, and Close controls sit in the detail header.
- Tabs: Overview and Images.
- Double-clicking a hero image opens the Images tab.
- Overview content is pack-specific: UK Public AI, World Pulse, Wikipedia, Micropedia, Pond Watch, API calls, or generic summary.
- Images tab renders gallery images with captions where available.

### Data And Output

- Static local packs can be loaded from `/data/...`.
- URL `?pack=...` can choose a pack path.
- Drag/drop or file input can load JSON, JSONL, full `pack.json`, plain item arrays, or OpenAPI 3.x specs.
- MCP resources can be loaded when an MCP HTTP endpoint is configured.
- Intro Markdown can be shown on first load and reopened.
- Collections persist locally.
- Tile/facet/sort preferences persist locally.
- Print selection uses print templates.
- AI export includes current records plus selected/highlighted flags.

## HMRC Workbench Implication

The HMRC workbench should move closer to this model by keeping a dense left control rail, making the card grid the primary interaction surface, preserving visible state transitions, supporting facet-colour and rollup gestures, and treating source-card links, context export, and narrative thumbnails as outputs of the same card-selection workflow.
"""


def main() -> None:
    NOTES_DIR.mkdir(parents=True, exist_ok=True)
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    outputs = {
        "seelinks-web-ui-anatomy.svg": draw_overview(),
        "seelinks-facet-tile-interactions.svg": draw_interactions(),
        "seelinks-views-detail-output.svg": draw_views(),
        "seelinks-data-state-flow.svg": draw_data_flow(),
    }
    for filename, content in outputs.items():
        (ASSET_DIR / filename).write_text(content, encoding="utf-8")
    NOTE_PATH.write_text(build_note(), encoding="utf-8")
    print(f"Wrote {len(outputs)} SeeLinks UI infographics and {NOTE_PATH.relative_to(PACK_DIR)}")


if __name__ == "__main__":
    main()
