#!/usr/bin/env python3
"""Build a SeeLinks-style datapack for the HMRC narrative corpus."""

from __future__ import annotations

import csv
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_PATH = Path(__file__).resolve()
PACK_DIR = SCRIPT_PATH.parents[1]
REPO_ROOT = SCRIPT_PATH.parents[3]
NARRATIVE_DIR = PACK_DIR / "narrative"
DATA_DIR = NARRATIVE_DIR / "data"
SEELINKS_DIR = NARRATIVE_DIR / "seelinks"
PACK_PATH = SEELINKS_DIR / "pack.json"
README_PATH = SEELINKS_DIR / "README.md"

GENERATED_MARKER = (
    "<!-- Generated by research/hmrc-beyond-hype/tools/build_narrative_seelinks_pack.py. -->"
)

CONVERSATION_KEYWORDS = (
    "SeeLinks",
    "Dark Data Workbench",
    "Challenge 2",
    "Browser AI",
    "MCP",
    "Codex",
    "agentic",
    "coding assistant",
)

VISUAL_FAMILIES = {
    "ai-native-engineering-blueprint": "AI-native engineering visuals",
    "ai-native-engineering-team-source-openai": "AI-native engineering visuals",
    "ai-native-engineering-team-workflow": "AI-native engineering visuals",
    "ai-benchmark-mastery-scoring-guide": "Market and evaluation visuals",
    "ai-coding-assistants-2026-evolution": "Market and evaluation visuals",
    "challenge-2-unlocking-dark-data": "Challenge 2 visuals",
    "dark-data-blueprint": "Challenge 2 visuals",
    "governing-ai-engineering": "Governance and assurance visuals",
}

TOPIC_GROUP_RULES = (
    ("Challenge 2 demo", ("challenge-2", "dark-data", "source-backed-answers", "talk-demo")),
    ("Evidence and provenance", ("provenance", "auditability", "traceability")),
    ("Agent workflow", ("agentic-coding", "workflow", "codex", "mcp")),
    ("Governance and risk", ("governance", "risk-boundaries", "security", "responsibility")),
    ("Evaluation and testing", ("evaluation", "validation", "testing")),
    ("Operating model", ("operating-model", "operations", "rollout", "planning", "review")),
    ("Tool market", ("ai-assistants", "market-scan", "timeline")),
    ("Talk delivery", ("hmrc", "public-sector", "audio-source", "navigation")),
)

GOVERNANCE_THEME_RULES = (
    ("Provenance", ("provenance", "source-backed", "citation", "evidence")),
    ("Validation", ("validation", "verify", "test", "benchmark", "eval")),
    ("Auditability", ("audit", "trace", "accountability", "record")),
    ("Security", ("security", "credential", "permission", "sandbox")),
    ("Data handling", ("data", "synthetic", "DPIA", "classification")),
    ("Human review", ("review", "approval", "sign-off", "ownership")),
    ("Operating model", ("operating-model", "workflow", "AGENTS.md", "changelog")),
    ("Source-backed answers", ("source-backed", "source backed", "dark data", "context")),
    ("Risk boundaries", ("risk", "boundary", "safety", "production", "critical")),
)

TALK_SECTIONS = (
    "Problem",
    "Repo",
    "Workflow",
    "Demo",
    "Strengths",
    "Limits",
    "Try first",
    "Close",
    "Q&A",
)


@dataclass(frozen=True)
class SourceDoc:
    path: Path
    source_family: str
    asset_type: str
    provenance_mode: str
    stage: str
    talk_section: str
    evidence_role: str
    image: str | None = None
    explicit_tags: tuple[str, ...] = ()


def repo_relative(path: Path) -> str:
    return path.resolve().relative_to(REPO_ROOT).as_posix()


def slugify(value: str, limit: int = 72) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug[:limit].strip("-") or "item"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def strip_frontmatter(text: str) -> str:
    return re.sub(r"^---\n[\s\S]*?\n---\n+", "", text, count=1)


def parse_frontmatter_tags(text: str) -> list[str]:
    match = re.match(r"---\n(?P<body>[\s\S]*?)\n---\n", text)
    if not match:
        return []
    tags: list[str] = []
    in_tags = False
    for line in match.group("body").splitlines():
        if line.strip() == "tags:":
            in_tags = True
            continue
        if in_tags and line.startswith("  - "):
            tags.append(line.removeprefix("  - ").strip().strip('"'))
            continue
        if in_tags and line and not line.startswith(" "):
            break
    return sorted(set(tags))


def extract_heading(text: str, fallback: str) -> str:
    body = strip_frontmatter(text)
    match = re.search(r"^#\s+(.+?)\s*$", body, flags=re.MULTILINE)
    if match:
        return match.group(1).strip()
    return fallback


def extract_section(text: str, heading: str) -> str:
    body = strip_frontmatter(text)
    pattern = rf"^##\s+{re.escape(heading)}\s*$([\s\S]*?)(?=^##\s+|\Z)"
    match = re.search(pattern, body, flags=re.MULTILINE | re.IGNORECASE)
    if not match:
        return ""
    return clean_markdown(match.group(1))


def clean_markdown(text: str, limit: int | None = None) -> str:
    cleaned = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    cleaned = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", cleaned)
    cleaned = re.sub(r"```[\s\S]*?```", "", cleaned)
    cleaned = re.sub(r"<!--[\s\S]*?-->", "", cleaned)
    cleaned = re.sub(r"^[-*]\s+", "", cleaned, flags=re.MULTILINE)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if limit and len(cleaned) > limit:
        return cleaned[: limit - 3].rstrip() + "..."
    return cleaned


def first_paragraph(text: str, fallback: str, limit: int = 700) -> str:
    body = strip_frontmatter(text)
    body = re.sub(r"^#\s+.+?$", "", body, count=1, flags=re.MULTILINE)
    paragraphs = [clean_markdown(part) for part in re.split(r"\n{2,}", body)]
    paragraphs = [
        part
        for part in paragraphs
        if part and not part.startswith("|") and not part.lower().startswith("## table of contents")
    ]
    return (paragraphs[0] if paragraphs else fallback)[:limit]


def word_count(text: str) -> int:
    return len(re.findall(r"\b[\w'-]+\b", strip_frontmatter(text)))


def estimate_screenfulls(text: str) -> int:
    return max(1, min(12, math.ceil(word_count(text) / 350)))


def infer_topic_groups(tags: list[str], text: str) -> list[str]:
    haystack = " ".join(tags).lower() + " " + text.lower()
    groups = [
        label
        for label, needles in TOPIC_GROUP_RULES
        if any(needle.lower() in haystack for needle in needles)
    ]
    return groups or ["Source material"]


def infer_governance_themes(tags: list[str], text: str) -> list[str]:
    haystack = " ".join(tags).lower() + " " + text.lower()
    themes = [
        label
        for label, needles in GOVERNANCE_THEME_RULES
        if any(needle.lower() in haystack for needle in needles)
    ]
    return themes[:5] or ["Source-backed answers"]


def infer_talk_section(source_id: str, item_number: int | None, tags: list[str], text: str) -> str:
    haystack = " ".join(tags).lower() + " " + text.lower()
    if source_id == "challenge-2-unlocking-dark-data":
        if item_number and item_number <= 3:
            return "Problem"
        return "Demo"
    if source_id == "dark-data-blueprint":
        return "Demo"
    if source_id == "governing-ai-engineering":
        return "Limits" if "risk" in haystack or "security" in haystack else "Try first"
    if source_id == "ai-native-engineering-blueprint":
        if item_number in {1, 2, 3, 4, 5}:
            return "Workflow"
        if item_number in {8, 9, 10, 11}:
            return "Strengths"
        return "Try first"
    if "question" in haystack or "q&a" in haystack:
        return "Q&A"
    if "security" in haystack or "risk" in haystack or "governance" in haystack:
        return "Limits"
    if "challenge 2" in haystack or "repo" in haystack or "workbench" in haystack:
        return "Repo"
    if "getting started" in haystack or "setup" in haystack or "try" in haystack:
        return "Try first"
    return "Workflow"


def infer_stage(source_id: str, item_number: int | None, tags: list[str], text: str) -> str:
    section = infer_talk_section(source_id, item_number, tags, text)
    if section == "Problem":
        return "Problem framing"
    if section == "Repo":
        return "Worked example"
    if section == "Demo":
        return "Provenance demo"
    if section == "Strengths":
        return "Contribution modes"
    if section == "Limits":
        return "Governance boundaries"
    if section == "Try first":
        return "Adoption path"
    if section == "Q&A":
        return "Question preparation"
    if "market-scan" in tags or "timeline" in tags:
        return "Market context"
    return "Workflow shift"


def infer_evidence_role(tags: list[str], text: str, asset_type: str) -> str:
    haystack = " ".join(tags).lower() + " " + text.lower()
    if asset_type in {"Slide", "PDF page", "Image"}:
        if "benchmark" in haystack or "evaluation" in haystack:
            return "Validation"
        if "risk" in haystack or "security" in haystack or "governance" in haystack:
            return "Control/risk"
        if "challenge-2" in tags or "workbench" in haystack:
            return "Demo object"
        return "Claim support"
    if "transcript" in haystack or "question" in haystack:
        return "Q&A prep"
    if "validation" in haystack or "report" in haystack:
        return "Validation"
    if "conversation" in haystack or "postmortem" in haystack:
        return "Source trail"
    if "getting started" in haystack or "setup" in haystack:
        return "Setup/start"
    return "Workflow pattern"


def source_doc_from_path(path: Path) -> SourceDoc:
    rel = repo_relative(path)
    lower = rel.lower()
    tags: tuple[str, ...] = ()
    if path.suffix.lower() == ".md":
        tags = tuple(parse_frontmatter_tags(read_text(path)))

    if "/narrative/notes/ai-coding-assistants-" in lower:
        if lower.endswith("ai-coding-assistants-q-and-a.md"):
            return SourceDoc(
                path,
                "HMRC talk research",
                "Narrative note",
                "Generated note",
                "Question preparation",
                "Q&A",
                "Q&A prep",
                explicit_tags=tags,
            )
        if lower.endswith("ai-coding-assistants-repo-case-study.md"):
            return SourceDoc(
                path,
                "HMRC talk research",
                "Narrative note",
                "Generated note",
                "Worked example",
                "Repo",
                "Demo object",
                explicit_tags=tags,
            )
        if lower.endswith(
            (
                "ai-coding-assistants-failure-modes.md",
                "ai-coding-assistants-public-sector-controls.md",
            )
        ):
            return SourceDoc(
                path,
                "HMRC talk research",
                "Narrative note",
                "Generated note",
                "Governance boundaries",
                "Limits",
                "Control/risk",
                explicit_tags=tags,
            )
        if lower.endswith("ai-coding-assistants-talk-track.md"):
            return SourceDoc(
                path,
                "HMRC talk research",
                "Narrative note",
                "Generated note",
                "Question preparation",
                "Q&A",
                "Q&A prep",
                explicit_tags=tags,
            )
        if lower.endswith("ai-coding-assistants-productivity-evidence.md"):
            return SourceDoc(
                path,
                "HMRC talk research",
                "Narrative note",
                "Generated note",
                "Question preparation",
                "Q&A",
                "Claim support",
                explicit_tags=tags,
            )
        if lower.endswith("ai-coding-assistants-source-register.md"):
            return SourceDoc(
                path,
                "HMRC talk research",
                "Narrative note",
                "Generated note",
                "Question preparation",
                "Q&A",
                "Source trail",
                explicit_tags=tags,
            )
        return SourceDoc(
            path,
            "HMRC talk research",
            "Narrative note",
            "Generated note",
            "Workflow shift",
            "Workflow",
            "Claim support",
            explicit_tags=tags,
        )
    if "/narrative/notes/" in lower or lower.endswith("/narrative/readme.md"):
        return SourceDoc(path, "Narrative guide", "Narrative note", "Generated note", "Navigation", "Close", "Source trail", explicit_tags=tags)
    if "/narrative/data/" in lower:
        return SourceDoc(path, "Narrative guide", "Narrative note", "Validation report", "Validation", "Try first", "Validation", explicit_tags=tags)
    if lower.endswith("/narrative/topics.md"):
        return SourceDoc(path, "Narrative guide", "Narrative note", "Generated index", "Navigation", "Q&A", "Source trail", explicit_tags=tags)
    if lower.endswith("/narrative/source-materials.md") or lower.endswith("/narrative/index.md") or lower.endswith("/narrative/overview.md") or lower.endswith("/narrative/narrative-arc.md"):
        return SourceDoc(path, "Narrative guide", "Narrative note", "Generated note", "Navigation", "Close", "Source trail", explicit_tags=tags)
    if "/transcripts/" in lower:
        return SourceDoc(path, "Audio dialogue", "Transcript", "Transcript", "Question preparation", "Q&A", "Q&A prep", explicit_tags=tags or ("audio-source",))
    if "postmortem-public/wiki/" in lower:
        return SourceDoc(path, "Conversation traces", "Conversation", "Conversation trace", "Worked example", "Repo", "Source trail", explicit_tags=tags)
    if "challenge-2/wiki/" in lower or lower.startswith("challenge-2/") or "/challenge-2/" in lower or lower.startswith("output/doc/challenge-2"):
        return SourceDoc(path, "Challenge 2 repo evidence", "Repo document", "Repo artifact", "Worked example", "Repo", "Demo object", explicit_tags=tags)
    if lower.endswith("01_source_register.csv"):
        return SourceDoc(path, "HMRC talk research", "Research briefing", "Imported source", "Question preparation", "Q&A", "Source trail", explicit_tags=("source-register",))
    if "/prompts/" in lower:
        return SourceDoc(path, "HMRC talk research", "Research briefing", "Imported source", "Navigation", "Close", "Source trail", explicit_tags=("prompt", "validation"))
    if lower.startswith("research/hmrc-beyond-hype/") or "/research/hmrc-beyond-hype/" in lower:
        return SourceDoc(path, "HMRC talk research", "Research briefing", "Imported source", "Market context", "Q&A", "Claim support", explicit_tags=tags)
    return SourceDoc(path, "Source material", "Document", "Imported source", "Source trail", "Q&A", "Source trail", explicit_tags=tags)


def collect_source_docs() -> list[SourceDoc]:
    paths: set[Path] = set()
    paths.update(path for path in NARRATIVE_DIR.glob("*.md") if path.is_file())
    paths.update(path for path in (NARRATIVE_DIR / "notes").glob("*.md") if path.is_file())
    for path in (NARRATIVE_DIR / "data").glob("*.md"):
        if path.name in {"visual_coverage.md", "narrative_validation_report.md"}:
            paths.add(path)
    paths.update(path for path in PACK_DIR.glob("[0-9][0-9]_*.md") if path.is_file())
    for path in [
        PACK_DIR / "01_source_register.csv",
        PACK_DIR / "prompts" / "00_master_prompt.md",
        PACK_DIR / "transcripts" / "README.md",
        PACK_DIR / "transcripts" / "pyannote_diarization_report.md",
        PACK_DIR / "transcripts" / "engineering-accountability-in-public-sector-ai.speakers.md",
        PACK_DIR / "transcripts" / "governing-agentic-ai-in-software-engineering.speakers.md",
        REPO_ROOT / "challenge-2" / "README.md",
        REPO_ROOT / "challenge-2" / "wiki" / "architecture.md",
        REPO_ROOT / "challenge-2" / "wiki" / "demonstration-guide.md",
        REPO_ROOT / "challenge-2" / "wiki" / "evaluation-benchmark.md",
        REPO_ROOT / "challenge-2" / "wiki" / "index.md",
        REPO_ROOT / "challenge-2" / "wiki" / "workbench.md",
        REPO_ROOT / "output" / "doc" / "challenge-2-realtime-delivery-report.md",
    ]:
        if path.exists():
            paths.add(path)

    for folder in [REPO_ROOT / "postmortem-public" / "wiki" / "exchanges", REPO_ROOT / "postmortem-public" / "wiki" / "sources"]:
        if not folder.exists():
            continue
        for path in folder.glob("*.md"):
            text = read_text(path)
            if any(keyword.lower() in text.lower() for keyword in CONVERSATION_KEYWORDS):
                paths.add(path)

    docs = [source_doc_from_path(path) for path in sorted(paths)]
    slide_sidecars = NARRATIVE_DIR / "slides"
    return [doc for doc in docs if slide_sidecars not in doc.path.parents]


def visual_items() -> list[dict[str, Any]]:
    coverage_path = DATA_DIR / "visual_coverage.csv"
    with coverage_path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))

    items: list[dict[str, Any]] = []
    for row in rows:
        sidecar = REPO_ROOT / row["sidecar_path"]
        text = read_text(sidecar)
        tags = sorted(set(filter(None, row["tags"].split(";"))))
        title = extract_heading(text, f"{row['source_id']} {row['item_number']}")
        asset_type = {
            "pptx-slide": "Slide",
            "pdf-page": "PDF page",
            "standalone-image": "Image",
        }.get(row["item_type"], row["item_type"])
        item_number = int(row["item_number"])
        item_id = f"hmrc-{slugify(row['source_id'], 46)}-{item_number:02d}"
        summary = (
            extract_section(text, "Claim Or Narrative Function")
            or extract_section(text, "Visual Description")
            or first_paragraph(text, title)
        )
        talk_section = infer_talk_section(row["source_id"], item_number, tags, text)
        stage = infer_stage(row["source_id"], item_number, tags, text)
        evidence_role = infer_evidence_role(tags, text, asset_type)
        governance_themes = infer_governance_themes(tags, text)
        topic_groups = infer_topic_groups(tags, text)
        screenfulls = estimate_screenfulls(text)
        asset_rel = row["asset_path"].removeprefix("research/hmrc-beyond-hype/narrative/")
        item = {
            "id": item_id,
            "name": title,
            "short_name": f"{VISUAL_FAMILIES.get(row['source_id'], row['source_id'])} {item_number:02d}",
            "image": f"/api/narrative-asset/{asset_rel}",
            "category_path": f"{VISUAL_FAMILIES.get(row['source_id'], row['source_id'])}/{asset_type}",
            "tile_subtitle": f"{talk_section} | {stage}",
            "info_text": clean_markdown(summary, 900),
            "properties": {
                "source_family": VISUAL_FAMILIES.get(row["source_id"], row["source_id"]),
                "asset_type": asset_type,
                "narrative_stage": stage,
                "talk_section": talk_section,
                "evidence_role": evidence_role,
                "governance_theme": governance_themes,
                "topic_group": topic_groups,
                "tags": tags,
                "provenance_mode": "Generated sidecar",
                "source_path": row["source_file"],
                "repo_path": row["sidecar_path"],
                "asset_path": row["asset_path"],
                "item_number": item_number,
                "screenfulls": screenfulls,
                "publication_status": row["publication_status"],
            },
            "links": [
                {"label": "Open narrative note", "href": f"/api/source-note/{item_id}", "kind": "seelinks-note"},
                {"label": "Open thumbnail", "href": f"/api/narrative-asset/{asset_rel}", "kind": "asset"},
                {"label": "Repository path", "href": row["sidecar_path"], "kind": "repo-path"},
            ],
        }
        items.append(item)
    return items


def doc_items(start_index: int) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for offset, doc in enumerate(collect_source_docs(), start=start_index):
        text = read_text(doc.path)
        title = extract_heading(text, doc.path.stem.replace("-", " ").replace("_", " ").title())
        tags = sorted(set(doc.explicit_tags) | set(re.findall(r"`([a-z][a-z0-9-]{2,})`", text)))
        tags = [tag for tag in tags if len(tag) <= 42][:18]
        full_summary = (
            extract_section(text, "Narrative Use")
            or extract_section(text, "Summary")
            or extract_section(text, "Key Talk Lines")
            or first_paragraph(text, title)
        )
        rel = repo_relative(doc.path)
        talk_section = doc.talk_section
        stage = doc.stage
        evidence_role = doc.evidence_role
        if doc.source_family == "HMRC talk research" and doc.asset_type != "Narrative note":
            talk_section = infer_talk_section("", None, tags, text)
            stage = infer_stage("", None, tags, text)
            evidence_role = infer_evidence_role(tags, text, doc.asset_type)
        governance_themes = infer_governance_themes(tags, text)
        topic_groups = infer_topic_groups(tags, text)
        item_id = f"hmrc-doc-{offset:03d}-{slugify(doc.path.stem, 42)}"
        items.append(
            {
                "id": item_id,
                "name": title,
                "short_name": title[:72],
                "icon": "/api/narrative-asset/assets/note-card.svg",
                "category_path": f"{doc.source_family}/{doc.asset_type}",
                "tile_subtitle": f"{talk_section} | {stage}",
                "info_text": clean_markdown(full_summary, 900),
                "properties": {
                    "source_family": doc.source_family,
                    "asset_type": doc.asset_type,
                    "narrative_stage": stage,
                    "talk_section": talk_section,
                    "evidence_role": evidence_role,
                    "governance_theme": governance_themes,
                    "topic_group": topic_groups,
                    "tags": tags,
                    "provenance_mode": doc.provenance_mode,
                    "source_path": rel,
                    "repo_path": rel,
                    "asset_path": "",
                    "screenfulls": estimate_screenfulls(text),
                    "publication_status": "tracked source material",
                },
                "links": [
                    {"label": "Open narrative note", "href": f"/api/source-note/{item_id}", "kind": "seelinks-note"},
                    {"label": "Repository path", "href": rel, "kind": "repo-path"},
                ],
            }
        )
    return items


def property_defs(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    fields = [
        ("source_family", "Source Family", "multi", "Narrative"),
        ("narrative_stage", "Narrative Stage", "multi", "Narrative"),
        ("talk_section", "Talk Section", "multi", "Narrative"),
        ("asset_type", "Asset Type", "multi", "Source"),
        ("evidence_role", "Evidence Role", "multi", "Evidence"),
        ("governance_theme", "Governance Theme", "multi", "Governance"),
        ("topic_group", "Topic Group", "multi", "Narrative"),
        ("provenance_mode", "Provenance Mode", "multi", "Source"),
        ("screenfulls", "Screenfulls", "number", "Readability"),
        ("tags", "Tags", "multi", "Source"),
    ]
    defs: list[dict[str, Any]] = []
    for order, (field_id, name, kind, section) in enumerate(fields):
        values: set[str] = set()
        for item in items:
            value = item["properties"].get(field_id)
            if isinstance(value, list):
                values.update(str(entry) for entry in value if str(entry).strip())
            elif value not in (None, "") and kind != "number":
                values.add(str(value))
        entry: dict[str, Any] = {
            "id": field_id,
            "name": name,
            "kind": kind,
            "section": section,
            "order": order,
        }
        if values and len(values) <= 80:
            entry["values"] = sorted(values)
        defs.append(entry)
    return defs


def build_collections(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_section: dict[str, list[str]] = {section: [] for section in TALK_SECTIONS}
    for item in items:
        section = str(item["properties"].get("talk_section", "Q&A"))
        if section in by_section:
            by_section[section].append(item["id"])
    collections = []
    for section in TALK_SECTIONS:
        ids = by_section[section]
        if not ids:
            continue
        collections.append(
            {
                "id": f"talk-{slugify(section)}",
                "name": f"Talk path: {section}",
                "description": f"Cards that support the {section.lower()} section of the HMRC AI agents talk.",
                "item_ids": ids,
                "created_at": "2026-05-11T00:00:00Z",
            }
        )
    return collections


def build_graph(items: list[dict[str, Any]]) -> dict[str, Any]:
    nodes: dict[str, dict[str, Any]] = {}
    edges: list[dict[str, Any]] = []
    for item in items:
        item_id = item["id"]
        nodes[item_id] = {
            "id": item_id,
            "kind": "source",
            "title": item["name"],
            "summary": item["info_text"],
            "image": item.get("image") or item.get("icon"),
        }
        for key, kind in [
            ("source_family", "category"),
            ("narrative_stage", "category"),
            ("talk_section", "category"),
            ("evidence_role", "category"),
            ("topic_group", "tag"),
            ("governance_theme", "tag"),
        ]:
            raw = item["properties"].get(key)
            values = raw if isinstance(raw, list) else [raw]
            for value in values:
                if not value:
                    continue
                node_id = f"{key}:{slugify(str(value), 54)}"
                nodes.setdefault(
                    node_id,
                    {
                        "id": node_id,
                        "kind": kind,
                        "title": str(value),
                    },
                )
                edges.append(
                    {
                        "id": f"{item_id}->{node_id}",
                        "kind": "tagged_with" if kind == "tag" else "has_category",
                        "from": item_id,
                        "to": node_id,
                    }
                )
    return {"nodes": list(nodes.values()), "edges": edges, "sources": [], "claims": []}


def build_pack() -> dict[str, Any]:
    items = visual_items()
    items.extend(doc_items(len(items) + 1))
    return {
        "meta": {
            "id": "hmrc-narrative-arc",
            "title": "HMRC Beyond The Hype Narrative Arc",
            "source": "local",
            "version": "1.0.0",
            "packKind": "hmrc-narrative",
            "fields": [
                "source_family",
                "narrative_stage",
                "talk_section",
                "asset_type",
                "evidence_role",
                "governance_theme",
                "topic_group",
                "provenance_mode",
                "screenfulls",
                "tags",
            ],
        },
        "properties": property_defs(items),
        "items": items,
        "collections": build_collections(items),
        "graph": build_graph(items),
    }


def write_readme(pack: dict[str, Any]) -> None:
    source_counts: dict[str, int] = {}
    for item in pack["items"]:
        family = item["properties"]["source_family"]
        source_counts[family] = source_counts.get(family, 0) + 1
    rows = "\n".join(
        f"| {family} | {count} |" for family, count in sorted(source_counts.items())
    )
    README_PATH.write_text(
        f"""{GENERATED_MARKER}
# HMRC Narrative SeeLinks Datapack

This folder contains a generated SeeLinks-style datapack for the HMRC Beyond the Hype
AI coding assistants to agents talk narrative.

## Load Path

- Workbench URL: `challenge-2/workbench/?pack=hmrc-narrative`
- Pack JSON: `research/hmrc-beyond-hype/narrative/seelinks/pack.json`

## Coverage

- Items: {len(pack["items"])}
- Facets: {len(pack["properties"])}
- Collections: {len(pack["collections"])}
- Graph nodes: {len(pack["graph"]["nodes"])}
- Graph edges: {len(pack["graph"]["edges"])}

## Source Families

| Source family | Items |
| --- | ---: |
{rows}

## Facets

The primary facets are source family, narrative stage, talk section, asset type,
evidence role, governance theme, topic group, provenance mode, screenfulls, and tags.
They are intentionally broad enough to span slide thumbnails, narrative notes,
transcripts, repo evidence, and conversation traces while keeping the first-level
choices small enough for a live talk.
""",
        encoding="utf-8",
    )


def main() -> int:
    SEELINKS_DIR.mkdir(parents=True, exist_ok=True)
    pack = build_pack()
    PACK_PATH.write_text(json.dumps(pack, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_readme(pack)
    print(
        "Wrote HMRC narrative SeeLinks datapack: "
        f"{repo_relative(PACK_PATH)} ({len(pack['items'])} items)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
