#!/usr/bin/env python3
"""Build GitHub-browsable sidecars for the HMRC talk visual imports."""

from __future__ import annotations

import csv
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path

from PIL import Image
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pypdf import PdfReader


SCRIPT_PATH = Path(__file__).resolve()
PACK_DIR = SCRIPT_PATH.parents[1]
REPO_ROOT = SCRIPT_PATH.parents[3]
IMPORT_DIR = PACK_DIR / "import"
NARRATIVE_DIR = PACK_DIR / "narrative"
SLIDES_DIR = NARRATIVE_DIR / "slides"
ASSETS_DIR = NARRATIVE_DIR / "assets" / "visuals"
DATA_DIR = NARRATIVE_DIR / "data"
NOTES_DIR = NARRATIVE_DIR / "notes"

THUMBNAIL_WIDTH = 960
GENERATED_MARKER = (
    "<!-- Generated by research/hmrc-beyond-hype/tools/build_narrative_sidecars.py. -->"
)


@dataclass(frozen=True)
class VisualSource:
    source_id: str
    title: str
    filename: str
    kind: str
    base_tags: tuple[str, ...]
    narrative_function: str
    caveat: str
    related_targets: tuple[str, ...]


VISUAL_SOURCES = (
    VisualSource(
        source_id="ai-native-engineering-blueprint",
        title="AI-Native Engineering Blueprint",
        filename="AI-Native_Engineering_Blueprint.pptx",
        kind="pptx",
        base_tags=("agentic-coding", "ai-assistants", "codex", "workflow", "validation"),
        narrative_function=(
            "Shows the talk's main workflow shift: engineering moves from typing code "
            "towards framing intent, giving context, steering agents, and validating evidence."
        ),
        caveat=(
            "Automated OCR from an image-only PowerPoint slide; verify exact wording before quoting."
        ),
        related_targets=(
            "04_agentic_coding_capabilities.md",
            "07_operating_model_for_public_sector_engineering.md",
            "transcripts/governing-agentic-ai-in-software-engineering.speakers.md",
        ),
    ),
    VisualSource(
        source_id="challenge-2-unlocking-dark-data",
        title="Challenge 2 Unlocking Dark Data",
        filename="Challenge_2_Unlocking_Dark_Data.pptx",
        kind="pptx",
        base_tags=(
            "challenge-2",
            "dark-data",
            "provenance",
            "source-backed-answers",
            "talk-demo",
        ),
        narrative_function=(
            "Frames the public-sector problem: guidance can exist but still be hard to find, "
            "structure, trust, and reuse as evidence-backed answers."
        ),
        caveat=(
            "Automated OCR from an image-only PowerPoint slide; verify exact wording before quoting."
        ),
        related_targets=(
            "06_repo_case_study_codex_build.md",
            "transcripts/engineering-accountability-in-public-sector-ai.speakers.md",
            "../challenge-2/wiki/workbench.md",
        ),
    ),
    VisualSource(
        source_id="dark-data-blueprint",
        title="Dark Data Blueprint",
        filename="Dark_Data_Blueprint.pptx",
        kind="pptx",
        base_tags=(
            "auditability",
            "challenge-2",
            "dark-data",
            "mcp",
            "provenance",
            "traceability",
        ),
        narrative_function=(
            "Explains the Challenge 2 architecture and why provenance, source preservation, "
            "and inspectable Markdown traces matter more than fluent answers alone."
        ),
        caveat=(
            "Automated OCR from an image-only PowerPoint slide; verify exact wording before quoting."
        ),
        related_targets=(
            "06_repo_case_study_codex_build.md",
            "../challenge-2/wiki/architecture.md",
            "../challenge-2/wiki/index.md",
        ),
    ),
    VisualSource(
        source_id="governing-ai-engineering",
        title="Governing AI Engineering",
        filename="Governing_AI_Engineering.pptx",
        kind="pptx",
        base_tags=(
            "governance",
            "hmrc",
            "public-sector",
            "risk-boundaries",
            "security",
            "validation",
        ),
        narrative_function=(
            "Sets the public-sector control frame: AI coding agents can accelerate work, "
            "but assurance, security sign-off, and policy ownership remain human and institutional duties."
        ),
        caveat=(
            "Automated OCR from an image-only PowerPoint slide; verify exact wording before quoting."
        ),
        related_targets=(
            "05_security_governance_public_sector.md",
            "07_operating_model_for_public_sector_engineering.md",
            "transcripts/governing-agentic-ai-in-software-engineering.speakers.md",
        ),
    ),
    VisualSource(
        source_id="ai-native-engineering-team-source-openai",
        title="AI-Native Engineering Team Source OpenAI",
        filename="AI-Native-Engineering-Team-source_openAI.pdf",
        kind="pdf",
        base_tags=("agentic-coding", "ai-assistants", "operating-model", "workflow"),
        narrative_function=(
            "Provides the external operating-model backdrop for AI-native engineering: "
            "plan, design, build, test, review, document, deploy, and maintain with agents."
        ),
        caveat=(
            "Text extracted from a local imported PDF and paired with a derived thumbnail; "
            "check the original before quoting exact wording."
        ),
        related_targets=(
            "04_agentic_coding_capabilities.md",
            "07_operating_model_for_public_sector_engineering.md",
            "notes/clawpilot-project-lobster.md",
        ),
    ),
    VisualSource(
        source_id="ai-benchmark-mastery-scoring-guide",
        title="AI Benchmark Mastery Scoring Guide",
        filename="AI Benchmark Mastery Scoring Guide.png",
        kind="png",
        base_tags=("evaluation", "validation", "talk-demo", "auditability"),
        narrative_function=(
            "Connects the talk demo to evaluation discipline: claims about assistant quality "
            "need scoring, repeatable checks, and source-backed review."
        ),
        caveat=(
            "Automated OCR from a standalone image; verify exact wording before quoting."
        ),
        related_targets=(
            "03_empirical_evidence_productivity.md",
            "06_repo_case_study_codex_build.md",
            "../challenge-2/wiki/evaluation-benchmark.md",
        ),
    ),
    VisualSource(
        source_id="ai-coding-assistants-2026-evolution",
        title="AI Coding Assistants 2026 Evolution",
        filename="AI Coding Assistants 2026 Evolution.png",
        kind="png",
        base_tags=("agentic-coding", "ai-assistants", "timeline", "workflow"),
        narrative_function=(
            "Shows the evolution from coding assistance to agentic engineering workflows "
            "that operate across repositories, tools, tests, and review loops."
        ),
        caveat=(
            "Automated OCR from a standalone image; verify exact wording before quoting."
        ),
        related_targets=(
            "02_timeline_ai_software_engineering.md",
            "04_agentic_coding_capabilities.md",
            "notes/clawpilot-project-lobster.md",
        ),
    ),
    VisualSource(
        source_id="ai-native-engineering-team-workflow",
        title="AI-Native Engineering Team Workflow",
        filename="AI-Native Engineering Team Workflow.png",
        kind="png",
        base_tags=("agentic-coding", "operating-model", "workflow", "validation"),
        narrative_function=(
            "Summarises the practical work pattern for the talk: delegate bounded work, "
            "review the diff, validate the evidence, and record decisions."
        ),
        caveat=(
            "Automated OCR from a standalone image; verify exact wording before quoting."
        ),
        related_targets=(
            "04_agentic_coding_capabilities.md",
            "07_operating_model_for_public_sector_engineering.md",
            "notes/clawpilot-project-lobster.md",
        ),
    ),
)


TAG_KEYWORDS = {
    "agentic-coding": ("agent", "agentic", "autonomous", "delegate", "workflow"),
    "ai-assistants": ("assistant", "copilot", "codex", "claude", "coding"),
    "auditability": ("audit", "trace", "evidence", "record", "accountability"),
    "challenge-2": ("challenge 2", "workbench", "wiki", "repository"),
    "dark-data": ("dark data", "findable", "published", "guidance", "source"),
    "evaluation": ("benchmark", "score", "eval", "rubric", "quality"),
    "governance": ("governance", "policy", "controls", "assurance", "review"),
    "mcp": ("mcp", "model context protocol", "context pack"),
    "provenance": ("provenance", "citation", "source-backed", "bundle"),
    "risk-boundaries": ("risk", "boundary", "limit", "critical", "safety"),
    "security": ("security", "secure", "threat", "credential", "permission"),
    "validation": ("validation", "test", "verify", "checks", "lint"),
}


NOTE_LINKS = {
    "02_timeline_ai_software_engineering.md": PACK_DIR / "02_timeline_ai_software_engineering.md",
    "03_empirical_evidence_productivity.md": PACK_DIR
    / "03_empirical_evidence_productivity.md",
    "04_agentic_coding_capabilities.md": PACK_DIR / "04_agentic_coding_capabilities.md",
    "05_security_governance_public_sector.md": PACK_DIR
    / "05_security_governance_public_sector.md",
    "06_repo_case_study_codex_build.md": PACK_DIR / "06_repo_case_study_codex_build.md",
    "07_operating_model_for_public_sector_engineering.md": PACK_DIR
    / "07_operating_model_for_public_sector_engineering.md",
    "transcripts/engineering-accountability-in-public-sector-ai.speakers.md": PACK_DIR
    / "transcripts"
    / "engineering-accountability-in-public-sector-ai.speakers.md",
    "transcripts/governing-agentic-ai-in-software-engineering.speakers.md": PACK_DIR
    / "transcripts"
    / "governing-agentic-ai-in-software-engineering.speakers.md",
    "../challenge-2/wiki/architecture.md": REPO_ROOT / "challenge-2" / "wiki" / "architecture.md",
    "../challenge-2/wiki/evaluation-benchmark.md": REPO_ROOT
    / "challenge-2"
    / "wiki"
    / "evaluation-benchmark.md",
    "../challenge-2/wiki/index.md": REPO_ROOT / "challenge-2" / "wiki" / "index.md",
    "../challenge-2/wiki/workbench.md": REPO_ROOT / "challenge-2" / "wiki" / "workbench.md",
    "notes/clawpilot-project-lobster.md": NOTES_DIR / "clawpilot-project-lobster.md",
}


def ascii_clean(value: str) -> str:
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2022": "-",
        "\u00a0": " ",
        "\u2122": "(TM)",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    return value.encode("ascii", "ignore").decode("ascii")


def collapse_spaced_letters(value: str) -> str:
    pattern = re.compile(r"\b(?:[A-Za-z]\s+){2,}[A-Za-z]\b")
    return pattern.sub(lambda match: match.group(0).replace(" ", ""), value)


def normalise_text(value: str) -> str:
    value = ascii_clean(value)
    value = collapse_spaced_letters(value)
    value = value.replace("\r\n", "\n").replace("\r", "\n")
    lines = []
    for line in value.splitlines():
        line = re.sub(r"[ \t]+", " ", line).strip()
        if line:
            lines.append(line)
    return "\n".join(lines).strip()


def sentence_lines(value: str) -> list[str]:
    lines: list[str] = []
    for line in normalise_text(value).splitlines():
        line = re.sub(r"^\W+", "", line).strip(" -|")
        if len(line) >= 4 and not re.fullmatch(r"[0-9. ]+", line):
            lines.append(line)
    return lines


def material_points(value: str, fallback: str) -> list[str]:
    lines = sentence_lines(value)
    if not lines:
        return [fallback]
    points: list[str] = []
    seen: set[str] = set()
    for line in lines:
        alpha_count = sum(character.isalpha() for character in line)
        alnum_ratio = sum(character.isalnum() for character in line) / max(len(line), 1)
        if alpha_count < 3 or alnum_ratio < 0.45:
            continue
        key = line.lower()
        if key in seen:
            continue
        seen.add(key)
        if len(line) > 180:
            chunks = re.split(r"(?<=[.;:])\s+", line)
            points.extend(chunk for chunk in chunks if len(chunk) >= 4)
        else:
            points.append(line)
    return points or [fallback]


def title_from_text(default: str, item_label: str, text: str) -> str:
    ignored_prefixes = ("version:", "repository:", "branch:", "commit:", "$$")
    for line in sentence_lines(text):
        cleaned = re.sub(r"^[0-9]+[.)]?\s*", "", line)
        lower = cleaned.lower()
        word_count = len(re.findall(r"[A-Za-z]{3,}", cleaned))
        alnum_ratio = sum(character.isalnum() for character in cleaned) / max(len(cleaned), 1)
        if (
            8 <= len(cleaned) <= 90
            and word_count >= 2
            and alnum_ratio >= 0.55
            and not lower.startswith(ignored_prefixes)
        ):
            return cleaned
    return f"{default} - {item_label}"


def tags_for(source: VisualSource, text: str) -> list[str]:
    found = set(source.base_tags)
    text_lower = text.lower()
    for tag, needles in TAG_KEYWORDS.items():
        if any(needle in text_lower for needle in needles):
            found.add(tag)
    return sorted(found)


def rel_link(from_file: Path, target: Path) -> str:
    return Path(os.path.relpath(target, from_file.parent)).as_posix()


def markdown_link(from_file: Path, label: str, target: Path) -> str:
    return f"[{label}]({rel_link(from_file, target)})"


def ensure_dirs() -> None:
    for directory in (SLIDES_DIR, ASSETS_DIR, DATA_DIR, NOTES_DIR):
        directory.mkdir(parents=True, exist_ok=True)


def remove_generated_tree(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def save_thumbnail(image: Image.Image, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    image = image.convert("RGB")
    if image.width > THUMBNAIL_WIDTH:
        ratio = THUMBNAIL_WIDTH / image.width
        height = max(1, int(image.height * ratio))
        image = image.resize((THUMBNAIL_WIDTH, height), Image.Resampling.LANCZOS)
    image.save(destination, "JPEG", quality=82, optimize=True)


def tesseract_path() -> str | None:
    candidate = shutil.which("tesseract")
    if candidate:
        return candidate
    fallback = Path("/opt/homebrew/bin/tesseract")
    if fallback.exists():
        return str(fallback)
    return None


def run_ocr(image: Image.Image) -> tuple[str, str]:
    executable = tesseract_path()
    if not executable:
        return "", "tesseract not available; OCR omitted"
    with tempfile.TemporaryDirectory() as tmp:
        image_path = Path(tmp) / "ocr-input.png"
        image.convert("RGB").save(image_path)
        result = subprocess.run(
            [executable, str(image_path), "stdout", "--psm", "6"],
            capture_output=True,
            text=True,
            check=False,
        )
    if result.returncode != 0:
        return "", normalise_text(result.stderr) or "tesseract OCR failed"
    return normalise_text(result.stdout), ""


def iter_picture_shapes(shapes):
    for shape in shapes:
        if shape.shape_type == MSO_SHAPE_TYPE.PICTURE:
            yield shape
        elif shape.shape_type == MSO_SHAPE_TYPE.GROUP:
            yield from iter_picture_shapes(shape.shapes)


def render_pdf_page(source_path: Path, page_number: int) -> Image.Image:
    executable = shutil.which("pdftoppm")
    if not executable and Path("/opt/homebrew/bin/pdftoppm").exists():
        executable = "/opt/homebrew/bin/pdftoppm"
    if not executable:
        raise RuntimeError("pdftoppm is required to render PDF page thumbnails")
    with tempfile.TemporaryDirectory() as tmp:
        prefix = Path(tmp) / "page"
        result = subprocess.run(
            [
                executable,
                "-jpeg",
                "-r",
                "144",
                "-f",
                str(page_number),
                "-l",
                str(page_number),
                "-singlefile",
                str(source_path),
                str(prefix),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or "pdftoppm failed")
        rendered = prefix.with_suffix(".jpg")
        with Image.open(rendered) as image:
            return image.copy()


def publication_status(source: VisualSource) -> str:
    if source.kind == "pdf":
        return "publishable derived thumbnail and text sidecar; raw imported PDF remains local"
    if source.kind == "pptx":
        return "publishable derived thumbnail and text sidecar; raw imported PowerPoint remains local"
    return "publishable derived thumbnail and text sidecar; raw imported PNG remains local"


def sidecar_body(
    source: VisualSource,
    source_path: Path,
    sidecar_path: Path,
    asset_path: Path,
    item_type: str,
    item_number: int,
    item_label: str,
    extracted_text: str,
    ocr_warning: str,
) -> str:
    fallback = (
        "The visual requires manual inspection because automated extraction produced little "
        "readable text."
    )
    points = material_points(extracted_text, fallback)
    tags = tags_for(source, extracted_text)
    if source.kind == "pdf":
        title = title_from_text(source.title, item_label, extracted_text)
    else:
        title = f"{source.title} - {item_label}"
    related_links = [
        markdown_link(sidecar_path, "Narrative arc", NARRATIVE_DIR / "narrative-arc.md"),
        markdown_link(sidecar_path, "Topic index", NARRATIVE_DIR / "topics.md"),
        markdown_link(sidecar_path, "Source material index", NARRATIVE_DIR / "source-materials.md"),
    ]
    for key in source.related_targets:
        target = NOTE_LINKS[key]
        if target.exists():
            label = Path(key).stem.replace("-", " ").replace("_", " ").title()
            related_links.append(markdown_link(sidecar_path, label, target))

    caveats = [source.caveat]
    if ocr_warning:
        caveats.append(ocr_warning)

    asset_link = rel_link(sidecar_path, asset_path)
    source_repo_path = source_path.relative_to(REPO_ROOT).as_posix()
    frontmatter_tags = "\n".join(f"  - {tag}" for tag in tags)
    material = "\n".join(f"- {point}" for point in points)
    related = "\n".join(f"- {link}" for link in related_links)
    caveat_text = "\n".join(f"- {caveat}" for caveat in caveats)
    extracted_block = (extracted_text or "(No reliable OCR or text extraction output.)").replace(
        "```", "'''"
    )

    return f"""{GENERATED_MARKER}
---
source_id: {source.source_id}
source_file: "{source_repo_path}"
item_type: {item_type}
item_number: {item_number}
asset: "{asset_path.relative_to(NARRATIVE_DIR).as_posix()}"
publication_status: "{publication_status(source)}"
tags:
{frontmatter_tags}
---

# {title}

![{source.title} {item_label}]({asset_link})

## Visual Description

This is {item_label.lower()} from `{source_repo_path}`. It is represented here by a small derived image so the narrative can be browsed on GitHub without publishing the raw import file.

## Claim Or Narrative Function

{source.narrative_function}

## Material Points Illustrated

{material}

## Related Narrative Links

{related}

## Publication Status

{publication_status(source)}.

## Caveats

{caveat_text}

## Extracted Visual Text

```text
{extracted_block}
```
"""


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def build_pptx(source: VisualSource) -> list[dict[str, str]]:
    source_path = IMPORT_DIR / source.filename
    presentation = Presentation(source_path)
    rows: list[dict[str, str]] = []
    source_dir = SLIDES_DIR / source.source_id
    asset_dir = ASSETS_DIR / source.source_id
    source_dir.mkdir(parents=True, exist_ok=True)
    asset_dir.mkdir(parents=True, exist_ok=True)

    for index, slide in enumerate(presentation.slides, start=1):
        pictures = list(iter_picture_shapes(slide.shapes))
        if not pictures:
            image = Image.new("RGB", (1280, 720), "white")
            extracted_text = ""
            ocr_warning = "No embedded picture was found on this image-only slide."
        else:
            with Image.open(BytesIO(pictures[0].image.blob)) as opened:
                image = opened.copy()
            extracted_text, ocr_warning = run_ocr(image)
        item_id = f"slide-{index:02d}"
        sidecar_path = source_dir / f"{item_id}.md"
        asset_path = asset_dir / f"{item_id}.jpg"
        save_thumbnail(image, asset_path)
        write_file(
            sidecar_path,
            sidecar_body(
                source,
                source_path,
                sidecar_path,
                asset_path,
                "pptx-slide",
                index,
                f"Slide {index:02d}",
                extracted_text,
                ocr_warning,
            ),
        )
        rows.append(row_for(source, source_path, sidecar_path, asset_path, "pptx-slide", index))
    write_source_index(source, rows)
    return rows


def build_pdf(source: VisualSource) -> list[dict[str, str]]:
    source_path = IMPORT_DIR / source.filename
    reader = PdfReader(str(source_path))
    rows: list[dict[str, str]] = []
    source_dir = SLIDES_DIR / source.source_id
    asset_dir = ASSETS_DIR / source.source_id
    source_dir.mkdir(parents=True, exist_ok=True)
    asset_dir.mkdir(parents=True, exist_ok=True)
    for index, page in enumerate(reader.pages, start=1):
        text = normalise_text(page.extract_text() or "")
        image = render_pdf_page(source_path, index)
        item_id = f"page-{index:02d}"
        sidecar_path = source_dir / f"{item_id}.md"
        asset_path = asset_dir / f"{item_id}.jpg"
        save_thumbnail(image, asset_path)
        write_file(
            sidecar_path,
            sidecar_body(
                source,
                source_path,
                sidecar_path,
                asset_path,
                "pdf-page",
                index,
                f"Page {index:02d}",
                text,
                "",
            ),
        )
        rows.append(row_for(source, source_path, sidecar_path, asset_path, "pdf-page", index))
    write_source_index(source, rows)
    return rows


def build_png(source: VisualSource) -> list[dict[str, str]]:
    source_path = IMPORT_DIR / source.filename
    with Image.open(source_path) as opened:
        image = opened.copy()
    extracted_text, ocr_warning = run_ocr(image)
    source_dir = SLIDES_DIR / source.source_id
    asset_dir = ASSETS_DIR / source.source_id
    source_dir.mkdir(parents=True, exist_ok=True)
    asset_dir.mkdir(parents=True, exist_ok=True)
    sidecar_path = source_dir / "image.md"
    asset_path = asset_dir / "image.jpg"
    save_thumbnail(image, asset_path)
    write_file(
        sidecar_path,
        sidecar_body(
            source,
            source_path,
            sidecar_path,
            asset_path,
            "standalone-image",
            1,
            "Image",
            extracted_text,
            ocr_warning,
        ),
    )
    rows = [row_for(source, source_path, sidecar_path, asset_path, "standalone-image", 1)]
    write_source_index(source, rows)
    return rows


def row_for(
    source: VisualSource,
    source_path: Path,
    sidecar_path: Path,
    asset_path: Path,
    item_type: str,
    index: int,
) -> dict[str, str]:
    sidecar_text = sidecar_path.read_text(encoding="utf-8")
    return {
        "source_id": source.source_id,
        "source_file": source_path.relative_to(REPO_ROOT).as_posix(),
        "item_type": item_type,
        "item_number": str(index),
        "sidecar_path": sidecar_path.relative_to(REPO_ROOT).as_posix(),
        "asset_path": asset_path.relative_to(REPO_ROOT).as_posix(),
        "tags": ";".join(tags_for(source, sidecar_text)),
        "publication_status": publication_status(source),
    }


def write_source_index(source: VisualSource, rows: list[dict[str, str]]) -> None:
    index_path = SLIDES_DIR / source.source_id / "index.md"
    links = "\n".join(
        f"- {markdown_link(index_path, row['item_type'].replace('-', ' ').title() + ' ' + row['item_number'].zfill(2), REPO_ROOT / row['sidecar_path'])}"
        for row in rows
    )
    tags = ", ".join(f"`{tag}`" for tag in source.base_tags)
    source_path = (IMPORT_DIR / source.filename).relative_to(REPO_ROOT).as_posix()
    write_file(
        index_path,
        f"""{GENERATED_MARKER}
# {source.title}

Source path: `{source_path}`

Coverage: {len(rows)} item(s), all represented by Markdown sidecars and derived image assets.

Primary tags: {tags}

Narrative function: {source.narrative_function}

## Sidecars

{links}
""",
    )


def build_clawpilot_note() -> None:
    path = NOTES_DIR / "clawpilot-project-lobster.md"
    local_source = IMPORT_DIR / "clawpilot.md"
    local_source_link = markdown_link(path, "local ClawPilot import brief", local_source)
    write_file(
        path,
        f"""{GENERATED_MARKER}
---
tags:
  - agentic-coding
  - ai-assistants
  - governance
  - identity
  - risk-boundaries
  - workflow
publication_status: "published narrative note; current claims require source recheck before live use"
---

# ClawPilot / Project Lobster Signal

This note incorporates the {local_source_link} as the local source-of-record for the sidebar. The shared ChatGPT research thread remains a prompted input and context trail, not final evidence on its own:
[shared ChatGPT thread](https://chatgpt.com/s/t_6a01debc15888191acf04212b95dd8b2).

## Narrative Use

Use this as a short "where agents are heading" sidebar in the HMRC talk. The useful point is not a product prediction; it is the enterprise pattern: persistent agents need identity, permissions, channels, observability, revocation, and evidence.

The local brief's most important distinction is that "ClawPilot" can refer to Microsoft's internal Project Lobster work and also to unrelated public/commercial Clawpilot services. Do not collapse those into one product claim.

## Evidence To Treat As Stronger

- The committed import brief records the working synthesis, source list, and public-sector evaluation lens: {local_source_link}.
- Omar Shahine's own write-up says he announced a Microsoft role focused on bringing OpenClaw and personal agents to Microsoft 365, and frames the lessons as harness, memory, security, graduated autonomy, identity, integration depth, proactive behaviour, and lived use: [Lobster Got Hired](https://www.omarknows.ai/p/lobster-got-hired).
- Microsoft Learn describes Microsoft Entra Agent ID as the identity and access foundation for Microsoft Agent 365, with governance of agent lifecycles, access, and audit activity: [Microsoft Entra Agent ID](https://learn.microsoft.com/en-us/entra/agent-id/).
- Microsoft 365 admin documentation says some agent instances receive their own Entra-backed identity, licence, mailbox, OneDrive, and Teams presence: [Understand agent details](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/agent-details?view=o365-worldwide#agent-instances).
- Microsoft's Agent 365 general availability post frames the enterprise problem as observing, governing, and securing agents across local, SaaS, and cloud environments, including local agents such as OpenClaw: [Microsoft Agent 365 GA post](https://www.microsoft.com/en-us/security/blog/2026/05/01/microsoft-agent-365-now-generally-available-expands-capabilities-and-integrations/).

## Evidence To Treat As Weaker

- The "ClawPilot" and "Project Lobster" labels, and internal-adoption numbers such as more than 3,000 daily Microsoft users by 1 May 2026, appear in secondary reporting and in the shared ChatGPT research thread. Treat these as "reported" until checked against a primary Microsoft or Omar Shahine source immediately before the talk.

## Talk Integration

- Link this to the talk's main boundary: as agents gain persistent identity and richer tool access, governance becomes part of the engineering product.
- Use it to explain why source-backed answers, audit trails, and review gates matter before public-sector teams move from coding assistants to agents that can act.
- Avoid presenting unverified internal Microsoft usage numbers as settled fact.
- Use the public-sector evaluation lens from the import brief: identity, least privilege, human approval, auditability, data governance, prompt-injection defence, supply chain, and recovery.

## Related Narrative Links

- [Narrative arc](../narrative-arc.md)
- [Topic index](../topics.md)
- [Source materials](../source-materials.md)
- [AI-Native Engineering Team Source OpenAI](../slides/ai-native-engineering-team-source-openai/index.md)
""",
    )


def write_core_narrative(rows: list[dict[str, str]]) -> None:
    by_source: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        by_source.setdefault(row["source_id"], []).append(row)

    index_path = NARRATIVE_DIR / "index.md"
    source_links = "\n".join(
        f"- {markdown_link(index_path, source.title, SLIDES_DIR / source.source_id / 'index.md')} "
        f"({len(by_source.get(source.source_id, []))} item(s))"
        for source in VISUAL_SOURCES
    )
    write_file(
        index_path,
        f"""{GENERATED_MARKER}
# From Typing Code To Steering Agents

This is the GitHub-browsable narrative pack for the HMRC Beyond the Hype talk.

Start here, then follow the argument through the overview, narrative arc, topic index, source-material register, and visual sidecars.

## Main Path

- [Overview](overview.md)
- [Narrative arc](narrative-arc.md)
- [Topic index](topics.md)
- [Source materials](source-materials.md)
- [Visual coverage report](data/visual_coverage.md)
- [Narrative validation report](data/narrative_validation_report.md)
- [Goal and acceptance criteria](README.md)

## Visual Source Sidecars

{source_links}

## Current External Sidebar

- [ClawPilot / Project Lobster signal](notes/clawpilot-project-lobster.md)
""",
    )

    write_file(
        NARRATIVE_DIR / "overview.md",
        f"""{GENERATED_MARKER}
# Overview

The talk is about the shift from typing code to steering agents in public-sector engineering.

The concrete case study is Challenge 2 from the AI Engineering Lab Codex build: government guidance exists, but it is scattered across PDFs, Word files, spreadsheets, and shared-drive style material. The engineering problem is not just whether AI can answer a question; it is whether a team can build source-backed, inspectable answers with provenance and validation.

The narrative pack keeps the imported visual material close to the evidence. Each slide, PDF page, and standalone image now has a sidecar note that describes the visible point, records tags and caveats, and links back into the research pack or repository artefacts.

Use the pack as a browseable companion during or after the talk rather than as a replacement for the live demo.

## Start Points

- [Narrative arc](narrative-arc.md)
- [Topic index](topics.md)
- [Source materials](source-materials.md)
- [Visual coverage report](data/visual_coverage.md)
""",
    )

    write_file(
        NARRATIVE_DIR / "narrative-arc.md",
        f"""{GENERATED_MARKER}
# Narrative Arc

1. Start with dark data: guidance exists, but it is buried across documents and is hard to find, structure, trust, and reuse.
2. Explain the workflow shift: engineers move from typing every line to framing intent, supplying context, constraining behaviour, reviewing diffs, and validating evidence.
3. Use Challenge 2 as the concrete case study: the generated wiki, Dark Data Workbench, source cards, evidence bundle, MCP tooling, and evaluation harness make provenance visible.
4. Show where agents help: exploration, scaffolding, refactoring, tests, documentation, report generation, source packaging, and validation support.
5. Draw the boundary: agents do not own security sign-off, production operation, data-risk decisions, or policy accountability.
6. Give the practical first step: pick low-risk internal material, keep raw data immutable, ask for small reviewable changes, require tests, inspect diffs, and record decisions.
7. Close on the main claim: coding agents are not just faster autocomplete; the productivity gain comes from disciplined workflow as much as model capability.

## Visual Evidence

- [Source material index](source-materials.md)
- [Topic index](topics.md)
- [Visual coverage report](data/visual_coverage.md)
""",
    )

    source_rows = []
    for source in VISUAL_SOURCES:
        count = len(by_source.get(source.source_id, []))
        source_rows.append(
            "| "
            + " | ".join(
                [
                    source.title,
                    f"`research/hmrc-beyond-hype/import/{source.filename}`",
                    source.kind,
                    str(count),
                    markdown_link(NARRATIVE_DIR / "source-materials.md", "sidecars", SLIDES_DIR / source.source_id / "index.md"),
                    "Raw source remains local; derived thumbnails and sidecars are published.",
                ]
            )
            + " |"
        )
    write_file(
        NARRATIVE_DIR / "source-materials.md",
        f"""{GENERATED_MARKER}
# Source Materials

This register lists the imported visual sources that have been turned into publication-safe sidecars. Raw imported binaries remain local unless explicitly selected for publication.

| Source | Local import path | Type | Covered items | Sidecars | Publication treatment |
| --- | --- | --- | ---: | --- | --- |
{chr(10).join(source_rows)}

## External Narrative Inputs

- [ClawPilot / Project Lobster signal](notes/clawpilot-project-lobster.md) incorporates `research/hmrc-beyond-hype/import/clawpilot.md` and the shared ChatGPT thread as inputs, and marks secondary claims that need rechecking before live use.
- `research/hmrc-beyond-hype/import/clawpilot.md` is a Markdown source input and is intended to be committed with the narrative pack.
""",
    )

    write_topics(rows)
    write_coverage(rows)


def write_topics(rows: list[dict[str, str]]) -> None:
    topics: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        for tag in row["tags"].split(";"):
            topics.setdefault(tag, []).append(row)

    path = NARRATIVE_DIR / "topics.md"
    sections: list[str] = []
    for tag in sorted(topics):
        links = "\n".join(
            f"- {markdown_link(path, Path(row['sidecar_path']).stem.replace('-', ' ').title(), REPO_ROOT / row['sidecar_path'])} "
            f"({Path(row['source_file']).name})"
            for row in topics[tag]
        )
        sections.append(f"## `{tag}`\n\n{links}")
    sections.append(
        "## `identity`\n\n"
        "- [ClawPilot / Project Lobster signal](notes/clawpilot-project-lobster.md)"
    )
    write_file(
        path,
        f"""{GENERATED_MARKER}
# Topic Index

Use these tags to jump into the visual sidecars and supporting narrative notes.

{chr(10).join(sections)}
""",
    )


def write_coverage(rows: list[dict[str, str]]) -> None:
    csv_path = DATA_DIR / "visual_coverage.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "source_id",
                "source_file",
                "item_type",
                "item_number",
                "sidecar_path",
                "asset_path",
                "tags",
                "publication_status",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)

    md_path = DATA_DIR / "visual_coverage.md"
    by_source: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        by_source.setdefault(row["source_id"], []).append(row)
    source_rows = []
    for source in VISUAL_SOURCES:
        source_rows.append(
            "| "
            + " | ".join(
                [
                    source.title,
                    source.kind,
                    str(len(by_source.get(source.source_id, []))),
                    str(len(by_source.get(source.source_id, []))),
                    markdown_link(md_path, "index", SLIDES_DIR / source.source_id / "index.md"),
                    "100%",
                ]
            )
            + " |"
        )
    item_links = "\n".join(
        f"- {markdown_link(md_path, row['source_id'] + ' ' + row['item_type'] + ' ' + row['item_number'].zfill(2), REPO_ROOT / row['sidecar_path'])}"
        for row in rows
    )
    write_file(
        md_path,
        f"""{GENERATED_MARKER}
# Visual Coverage

Coverage target: every imported PowerPoint slide, PDF page, and standalone image in the current HMRC talk import drop.

Total covered items: {len(rows)}.

| Source | Type | Expected items | Covered sidecars | Source index | Coverage |
| --- | --- | ---: | ---: | --- | ---: |
{chr(10).join(source_rows)}

## Item-Level Coverage

{item_links}

Machine-readable coverage is recorded in [visual_coverage.csv](visual_coverage.csv).
""",
    )


def main() -> int:
    ensure_dirs()
    remove_generated_tree(SLIDES_DIR)
    remove_generated_tree(ASSETS_DIR)
    rows: list[dict[str, str]] = []
    for source in VISUAL_SOURCES:
        if source.kind == "pptx":
            built = build_pptx(source)
        elif source.kind == "pdf":
            built = build_pdf(source)
        elif source.kind == "png":
            built = build_png(source)
        else:
            raise ValueError(f"Unhandled source kind: {source.kind}")
        rows.extend(built)
        print(f"{source.filename}: {len(built)} item(s) covered")

    build_clawpilot_note()
    write_core_narrative(rows)
    print(f"Total visual sidecars covered: {len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
